name: Android CI - Build Debug APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 2: Setup Java 17
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0

      # Step 4: Generate Gradle wrapper (so ./gradlew works)
      - name: Generate Gradle Wrapper
        run: gradle wrapper --gradle-version 8.5

      # Step 5: Make wrapper executable (Linux/Mac)
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Step 6: Build debug APK using wrapper
      - name: Build debug APK
        run: ./gradlew assembleDebug --no-daemon

      # Step 7: Upload APK artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: guardianconnect-apk
          path: app/build/outputs/apk/debug/app-debug.apk
