name: Android CI - Build Debug APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # Setup Java 17
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Setup Android SDK (corrected)
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: '9477386'
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0
          accept-android-sdk-licenses: true

      # Generate Gradle Wrapper
      - name: Generate Gradle Wrapper
        run: gradle wrapper --gradle-version 8.5

      # Make wrapper executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Build APK
      - name: Build debug APK
        run: ./gradlew assembleDebug --no-daemon

      # Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: guardianconnect-apk
          path: app/build/outputs/apk/debug/app-debug.apk
